name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish-env

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Module
        working-directory: ./packages/module
        run: pnpm run generate
        env:
          NODE_ENV: production

      - name: push npm
        working-directory: ./packages/module
        run: pnpm publish --no-git-checks
